# Generated by Django 4.1.7 on 2023-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('type_of_user', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=100)),
                ('otp_verified', models.BooleanField(default=False)),
                ('private_key', models.CharField(max_length=100)),
            ],
        ),
    ]
