# Generated by Django 4.1.7 on 2023-05-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangofy_backend_a', '0006_userprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojects',
            name='project_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='project_name',
            field=models.CharField(max_length=1000),
        ),
    ]
