# Generated by Django 4.1.7 on 2023-05-19 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangofy_backend_a', '0007_alter_userprojects_project_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 19, 11, 7, 38, 629030, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprojects',
            name='github_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprojects',
            name='github_repo_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
