# Generated by Django 4.1.7 on 2023-05-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangofy_backend_a', '0008_userprojects_created_at_userprojects_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
